requires_meltano: ">=4.0.0"
default_environment: dev
project_id: olist-meltano

environments:
  - name: dev
  
plugins:
  extractors:
    - name: tap-postgres
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
      config:
        host: ${POSTGRES_HOST}
        port: ${POSTGRES_PORT}
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        database: olist
        ssl: true
        filter_schemas:
          - oltp

      select:
        - oltp-olist_customers.*
        - oltp-olist_orders.*
        - oltp-olist_order_items.*
        - oltp-olist_order_payments.*
        - oltp-olist_order_reviews.*
        - oltp-olist_products.*
        - oltp-olist_sellers.*
        - oltp-product_category_name_translation.*
        # - oltp-olist_geolocation.* # handled separately as append-only

      metadata:
        oltp-olist_customers:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - customer_id

        # oltp-olist_geolocation:
        #   replication-method: INCREMENTAL
        #   replication-key: updated_at
        #   #key-properties: (olist_geolocation has no natural primary key)
        #     #- geolocation_id

        oltp-olist_orders:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - order_id

        oltp-olist_order_items:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - order_id
            - order_item_id

        oltp-olist_order_payments:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - order_id
            - payment_sequential

        oltp-olist_order_reviews:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - review_id
            - order_id

        oltp-olist_products:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - product_id

        oltp-olist_sellers:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - seller_id

        oltp-product_category_name_translation:
          replication-method: INCREMENTAL
          replication-key: updated_at
          key-properties:
            - product_category_name

    - name: tap-postgres-geolocation
      inherit_from: tap-postgres
      select:
        - oltp-olist_geolocation.*
      
      metadata:
        oltp-olist_geolocation:
          replication-method: INCREMENTAL
          replication-key: updated_at
          #no key-properties: as olist_geolocation has no natural primary key

  loaders:
    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
      config:
        project: sctp-team2-project2-elt
        # project: western-beanbag-496804-a4 # johnphs GCP project
        dataset: olin_bronze
        credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}
        location: US
        method: batch_job
        denormalized: true
        flattening_enabled: true
        flattening_max_depth: 1
        upsert: true
        dedupe_before_upsert: true

    - name: target-bigquery-append
      inherit_from: target-bigquery
      config:
        upsert: false
        dedupe_before_upsert: false
        overwrite: false

jobs:
  - name: postgres-to-bigquery-bronze
    tasks:
      - tap-postgres target-bigquery
  
  - name: postgres-geolocation-to-bigquery-bronze
    tasks:
      - tap-postgres-geolocation target-bigquery-append

  - name: postgres-all-to-bigquery-bronze
    tasks:
      - tap-postgres target-bigquery
      - tap-postgres-geolocation target-bigquery-append