olist_dbt_test:
  outputs:
    dev:
      dataset: bt_olist_dbt_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: sctp-team2-project2-elt
      threads: 1
      type: bigquery
  target: dev